[package]
name = "android-ffi"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "hns_dane_browser_ffi"
crate-type = ["cdylib", "rlib"]

[dependencies]
hns-mobile-platform-runtime.workspace = true
hns-header-consensus.workspace = true
hns-light-sync.workspace = true
hns-wallet-ffi.workspace = true
hns-wallet-mobile.workspace = true
hns-wallet-types.workspace = true
jni.workspace = true
serde_json = "1"
