[package]
name = "hns-header-snapshot-exporter"
version = "0.1.0"
edition = "2024"
license = "PolyForm-Noncommercial-1.0.0"

[workspace]

[dependencies]
hns-chain = { package = "hns-browser-chain", version = "=0.2.0", git = "https://github.com/handshake-rs/hns-dane-engine.git", rev = "b8bdfbf7e234e64166886ade6f79d698e23056af" }
hns-core = { package = "hns-browser-primitives", version = "=0.2.0", git = "https://github.com/handshake-rs/hns-dane-engine.git", rev = "b8bdfbf7e234e64166886ade6f79d698e23056af" }
hns-p2p = { package = "hns-browser-p2p", version = "=0.2.0", git = "https://github.com/handshake-rs/hns-dane-engine.git", rev = "b8bdfbf7e234e64166886ade6f79d698e23056af" }
hns-sync = { package = "hns-browser-sync", version = "=0.2.0", git = "https://github.com/handshake-rs/hns-dane-engine.git", rev = "b8bdfbf7e234e64166886ade6f79d698e23056af" }
